AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  StockDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: stock_data/
      Handler: lambda.lambda_handler
      Runtime: python3.9
      Timeout: 60
      Architectures:
        - x86_64

  TwitterDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: stock_data/
      Handler: lambda.lambda_handler
      Runtime: python3.9
      Timeout: 60
      Architectures:
        - x86_64
